set nocompatible
set number

autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

map ; :Files<CR>

set cursorline
hi cursorline cterm=none term=none
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
highlight CursorLine guibg=#303000 ctermbg=234


filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'itchyny/lightline.vim'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'mattn/emmet-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-surround'
Plugin 'w0rp/ale'
Plugin 'chriskempson/base16-vim'

call vundle#end()
filetype plugin indent on

let base16colorspace=256  " Access colors present in 256 colorspace
colorscheme base16-eighties

:set list
:set listchars=tab:→\ ,space:·,nbsp:␣,trail:•,eol:$,precedes:«,extends:» 